baseURL = 'https://narcologia-24.ru/'
languageCode = 'ru-ru'
title = 'Центр медицинской и психологической помощи'
# theme = 'hugo-serif-theme'

[params]
  description = "Центр медицинской и психологической помощи - лечение алкоголизма, наркомании, реабилитация зависимых"
  phone1 = "8 800 300 61 03"
  phone2 = "8 495 532 44 03"
  address = "Ижевск, ул. Азина 150 к1"
  license = "Л041-01137-77/01242550"
  
[menu]
  [[menu.main]]
    identifier = "zapoy"
    name = "Вывод из запоя"
    url = "/zapoy/"
    weight = -1
  [[menu.main]]
    identifier = "narcology"
    name = "Наркология"
    url = "/narcology/"
    weight = 1
  [[menu.main]]
    identifier = "psychiatry"
    name = "Психиатрия"
    url = "/psychiatry/"
    weight = 2
  [[menu.main]]
    identifier = "rehabilitation"
    name = "Реабилитация"
    url = "/rehabilitation/"
    weight = 3
  [[menu.main]]
    identifier = "psychology"
    name = "Психология"
    url = "/psychology/"
    weight = 4
  [[menu.main]]
    identifier = "therapy"
    name = "Терапия"
    url = "/therapy/"
    weight = 5
  [[menu.main]]
    identifier = "info"
    name = "О нас"
    url = "#"
    weight = 6
  [[menu.main]]
    identifier = "about"
    name = "О нас"
    url = "/about/"
    weight = 1
    parent = "info"
  [[menu.main]]
    identifier = "prices"
    name = "Цены"
    url = "/prices/"
    weight = 2
    parent = "info"
  [[menu.main]]
    identifier = "doctors"
    name = "Врачи"
    url = "/doctors/"
    weight = 3
    parent = "info"
  [[menu.main]]
    identifier = "posts"
    name = "Статьи"
    url = "/posts/"
    weight = 4
    parent = "info"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
